function(print LEVEL STR)
    if(${LEVEL} STREQUAL ERROR)
        message("[ERROR]: ${STR}")
    elseif(${LEVEL} STREQUAL INFO)
        message("[INFO]: ${STR}")
    elseif(${LEVEL} STREQUAL DEBUG)
        message("[DEBUG]: ${STR}")
    endif()
endfunction()